export const CARGAR_SPINNER = 'CARGAR_SPINNER';
export const OBTENER_PELIS_CAROUSEL = 'OBTENER_PELIS_CAROUSEL';
export const OBTENER_ULTIMAS_PELIS = 'OBTENER_ULTIMAS_PELIS';
export const OBTENER_POPULARES = 'OBTENER_POPULARES'
export const OBTENER_RANKING = 'OBTENER_RANKING'
export const OBTENER_PROXIMAS = 'OBTENER_TOP_PELICULAS'
export const OBTENER_PELICULAS = 'OBTENER_PELICULAS'
export const CARGAR_ULTIMO_FILTER='CARGAR_ULTIMO_FILTER'

/*____________________*/

export const OBTENER_SERIES_POPULARES='OBTENER_SERIES_POPULARES'
export const RESET_SERIES='RESET_SERIES';